# Generated by Django 5.2.5 on 2026-02-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_alter_pantryitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
