# Generated by Django 5.2.5 on 2026-02-20 17:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_alter_pantryitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantryitem',
            name='user',
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('protein', 'Protein'), ('spice', 'Spice'), ('Baking', 'Baking'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 2, 27)),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
