# Generated by Django 5.2.5 on 2026-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_alter_pantryitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('protein', 'Protein'), ('spice', 'Spice'), ('baking', 'Baking'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
