# Generated by Django 5.2.5 on 2026-02-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favoriterecipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbs_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
