# Generated by Django 5.2.5 on 2026-02-20 19:07

import pantry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_remove_pantryitem_user_pantryitem_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='expiry_date',
            field=models.DateField(default=pantry.models.default_expiry_date),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
