# Generated by Django 5.2.5 on 2026-02-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_alter_pantryitem_category_alter_pantryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('pcs', 'Pieces')], default='pcs', max_length=10),
        ),
    ]
